[package]
name = "mm2-libp2p"
version = "0.1.0"
authors = ["Artem Pikulin <ortgma@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
atomicdex-gossipsub = { path = "../gossipsub" }
futures = { version = "0.3.1", package = "futures", features = ["compat", "async-await"] }
hex = "0.4.2"
libp2p = "0.21.1"
libsecp256k1 = "0.3.5"
num-bigint = { version = "0.2", features = ["serde", "std"] }
num-rational = { version = "0.2", features = ["serde", "bigint", "bigint-std"] }
rand = { version = "0.7", features = ["std"] }
rmp-serde = "0.14.3"
serde = "1.0"
serde_bytes = "0.11.5"
serde_derive = "1.0"
sha2 = "0.9.0"
wasm-timer = "0.2.4"